Advance Section/advDjango/advDjango/urls.py
from django.contrib import admin
from django.urls import path
from adv_app import views
from django.conf.urls import url,include

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',views.IndexView.as_view()),
    url(r'^adv_app/',include('adv_app.urls',namespace='adv_app')),
    
    
]

Advance Section/advDjango/adv_app/urls.py
from django.conf.urls import url
from adv_app import views




app_name = 'adv_app'

urlpatterns = [
    url(r'^$',views.SchoolListView.as_view(),name='list'),
    url(r'^$',views.SchoolDetailView.as_view(),name='detail'),

]

Advance Section/advDjango/adv_app/models.py
from django.db import models

# Create your models here.

class School(models.Model):
    name = models.CharField(max_length=256)
    principle = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school=models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)


    def __str__(self):
        return self.name

Advance Section/advDjango/adv_app/views.py
from django.shortcuts import render
from django.views.generic import View,TemplateView,ListView,DetailView
from . import  models
# Create your views here.


class IndexView(TemplateView):
    template_name = 'adv_app/index.html'


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['injectme']='Basic Injection'

        return context


class SchoolListView(ListView):
    context_object_name = 'school_list'
    model = models.School


class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'adv_app/school_detail.html'

Advance Section/advDjango/adv_app/templates/adv_app/adv_app_base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>HOME</title>
</head>
<body>

    
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="">Brand</a></li>

                    <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>

                    <li> <a class="navbar-link" href="{% url 'adv_app:list' %}">School</a> </li>

                    <li> <a class="navbar-link" href="{% url 'adv_app:detail' %">Schools Detail</a> </li>




                </ul>

            </div>

        </nav>
    

    <div class="container">
      {% block body_block %}

      {% endblock %}
    </div>

</div>
    
</body>
</html>

Advance Section/advDjango/adv_app/templates/adv_app/school_detail.html
{% extends 'adv_app/adv_app_basic.html' %}
{% block body_block %}
  <div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>Id_num: {{school_details.id}}</p>
    <p><li></li>Name: {{school_details.name}}</p>
    <p>Principal: {{school_details.principal}}</p>
    <p>Location: {{school_details.location}}</p>
    <h3>Students:</h3>

      {% for student in school_details.students.all %}
        <p>{{student.name}} who is {{student.age}} years old.</p>
      {% endfor %}

  </div>
  <div class="container">
    <p><a class='btn btn-warning' href="{% url 'basic_app:update' pk=school_details.pk %}">Update</a></p>

  </div>

{% endblock %}

Advance Section/advDjango/adv_app/templates/adv_app/school_list.html
{% extends "adv_app/adv_app_base.html" %}

{% block body_block %}
  <div class="jumbotron">

    <h1>Welcome to the List of Schools Page!</h1>
      <ol>
        {% for school in school_list %}
          <h2><li>{{school.name}}</li></h2>
        {% endfor %}
      </ol>

  </div>


{% endblock %}

Advance Section/advDjango/templates/adv_app/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>HOME</title>
</head>
<body>

    
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">

                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="">Brand</a></li>

                    <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>


                    <li> <a class="navbar-link" href="{% url 'adv_app:list' %}">School</a> </li>




                </ul>

            </div>

        </nav>
    

    {% comment %} <div class="container">

        {% block body_block %}

        <!-- inherit templates here  -->

        {% endblock %}

    </div> {% endcomment %}
    
</body>
</html>

Advance Section/advDjango/templates/adv_app/index.html
{% include 'adv_app/basic.html' %}

{% block body %}

<h1>Hello</h1>

<h1>Injected contents : {{ injectme }}</h1>

{% endblock  %}