LevelFive/template_project/app_template/urls.py
from django.conf.urls import url
from app_template import views


# Template Tagging

app_name = 'template_app'

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^signup/',views.signupform,name='signup'),
    url(r'^basic/',views.basic,name='basic'),
    url(r'^other/',views.other,name='other'),
    url(r'^relative_template/',views.relateive_template,name='relative_template'),
    url(r'^user_login/$',views.user_login,name='user_login'),


]

LevelFive/template_project/template_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
from app_template import views

urlpatterns = [
    path(r'',views.index,name='index'),
    path(r'basic_app/',include('app_template.urls')),
    path('admin/', admin.site.urls),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'special/',views.special,name='special'),

]

LevelFive/template_project/app_template/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class UserProfileInfo(models.Model):

    user=models.OneToOneField(User,on_delete=models.CASCADE)  #on_delete=models.CASCADE field is required!

    #aditional 
    portfolio_site  = models.URLField(blank=True)


    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)


    def __str__(self):
        return self.user.username # username is a default attribute of oneToOneField()

LevelFive/template_project/app_template/forms.py
from django  import forms
from django.contrib.auth.models import User
from app_template.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())


    class Meta():
        model  = User
        fields = ('username','email','password')



class UserProfileInfoForm(forms.ModelForm):

    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

LevelFive/template_project/app_template/views.py
from django.shortcuts import render
from app_template.forms import UserProfileInfoForm,UserForm
from django.core import validators
from django import forms


#
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect,HttpResponse 
# from django.core.urlresolvers import reverse  #django 2 removes urlresolvers
from django.urls import reverse

from django.contrib.auth.decorators import login_required


# Create your views here.

def index(request):
    contest_dict = {'text':"Hello world!"}
    return render(request,'app_template/index.html',contest_dict)

@login_required
def special(request):
    return HttpResponse("You are loggedin , Nice!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def basic(request):
    return render(request,'app_template/basic.html')

def other(request):
    return render(request,'app_template/other.html')

def relateive_template(request):
    return render(
            request,
            'app_template/relative_url_template.html'
        )



def signupform(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)  #hashing the password
            user.save()

            profile = profile_form.save(commit=False)

            profile.user = user



            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']


            profile.save()


            registered = True


        else :
             print(user_form.errors,profile_form.errors)

    else :
        user_form  = UserForm()

        profile_form = UserProfileInfoForm()


    return render(
            request,
            'app_template/signup.html',
                {
                    'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered,
                }
        )



def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')


        user = authenticate(username = username,password=password)

        if user :
            if user.is_active:
                login(request,user)

                return HttpResponseRedirect(reverse('index'))

            else :
                return HttpResponse("Account is not Active")


        else :
            print("Someone tried to login and failed")

            print("Username : {} and password {}".format(username,password))


            return HttpResponse("Invalid login detailed supplied")


    else :
        return render(request,'app_template/login.html')

LevelFive/template_project/templates/app_template/basic.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>HOME</title>
</head>
<body>

    
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container-fluid">

                <ul class="nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'template_app:index' %}">Brand</a></li>

                    <li> <a class="navbar-link" href="{% url 'admin:index' %}">Admin</a> </li>

                    <li> <a class="navbar-link" href="{% url 'template_app:other' %}">Other</a> </li>

                    {% if user.is_authenticated %}

                        <li><a class="navbar-link" href="{% url 'logout' %}">LogOut</a></li>


                    {% else %}

                        <li><a class="navbar-link" href="{% url 'template_app:user_login' %}">LogIn</a></li>

                        <li><a class="navbar-link" href="{% url 'template_app:signup' %}" >Signup here</a></li>


                    {% endif %}



                </ul>

            </div>

        </nav>
    

    <div class="container">

        {% block body_block %}

        <!-- inherit templates here  -->

        {% endblock %}

    </div>
    
</body>
</html>

LevelFive/template_project/templates/app_template/index.html
<!DOCTYPE html>

{% include "app_template/basic.html" %}

{% block body_block %}

    <div class="container">
        <h1>Welcome to Index</h1>
        <h2>This is a index.html page showing !</h2>

        <h1>{{ text|cut:'world' }}</h1>

        
    </div>

{% endblock %}

LevelFive/template_project/templates/app_template/login.html
{% extends 'app_template/basic.html' %}

{% block body_block %}


<div class="jumbotron">

    <h1>please Login</h1>

    <form action="{%  url 'template_app:user_login' %}" class="form form-group" method="POST">

        {% csrf_token %}

        <label for="username" class="form form-control">Username : </label>
        <input type="text" class="form form-control" name="username" placeholder="Enter Username" >

        <label for="password" class="form form-control">Password : </label>
        <input type="password" class="form form-control" name="password">

        <input  type="submit" value="Login" class="form btn btn-primary">

    </form>

</div>

{% endblock %}

LevelFive/template_project/templates/app_template/other.html
<!DOCTYPE html>  <!--this is a must here--> 

{% extends 'app_template/basic.html' %}

{% block body_block %}

<div class="jumbotron">
  <h3>Welcome to django!Other.html</h3>
</div>

{% endblock %}

LevelFive/template_project/templates/app_template/relative_url_template.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>HOME</title>
</head>
<body>

    <div class="container">
        <div class="jumbotron">
            <h3>Welcome to django!</h3>
            
            <h2>Here are the links below :</h2>
            <a href="{% url 'template_app:index' %}" >Index</a>
            <a href="{% url 'template_app:basic' %}">Basic</a><br>
            <a href="{% url 'template_app:other' %}">Other</a><br>
            <a href="{% url 'template_app:signup' %}">Signup</a><br>
            <a href="{% url 'template_app:relative_template' %}">Relative_template</a><br>
        </div>
    </div>
    
</body>
</html>

LevelFive/template_project/templates/app_template/signup.html
<!DOCTYPE html>
{% load static %}
{% load crispy_forms_tags %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
    />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <title>Sign Up</title>
</head>
<body>

    <div class="well">

        {% if registered %}

            <h1>Thank You for Your registration!</h1>

        {% else  %}

        <h1>Register here :</h1>

        <h3>Fill out the form !</h3>

        <form method="POST" class="form-group" enctype="multipart/form-data">
            <!-- {{form.as_p}}  -->
            
            {% csrf_token %}

            {{ user_form|crispy }}

            {{profile_form|crispy}}

            <input class="btn btn-primary" type="submit" value="submit" >
        </form>

        {% endif %}
    </div>


    <div class="container">
        <h3>Welcome to django!</h3>
        
        <h2>Here are the links below :</h2>
        <a href="{% url 'template_app:index' %}" >Index</a>
        <a href="{% url 'template_app:basic' %}">Basic</a><br>
        <a href="{% url 'template_app:other' %}">Other</a><br>
        <a href="{% url 'template_app:signup' %}">Signup</a><br>
        <a href="{% url 'template_app:relative_template' %}">Relative_template</a><br>
    </div>
    
</body>
</html>